packages:
  - apps/*
  - packages/*

publicHoistPattern:
  - '@base-ui/react'
  - class-variance-authority
  - clsx
  - embla-carousel-react
  - react-day-picker
  - react-hook-form
  - react-is
  - react-resizable-panels
  - recharts
  - tailwind-merge

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
