// Writes components/mdx/demo-map.generated.ts from the demos registry: one
// next/dynamic entry per demo. A docs page then ships only the chunks of the
// demos it renders, instead of every demo reachable from a template-literal
// import in the shared docs route.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const REGISTRY = path.join(process.cwd(), "../../packages/registry/demos/registry.json");
const OUTPUT = path.join(process.cwd(), "components/mdx/demo-map.generated.ts");

type RegistryItem = { name: string; files: { path: string }[] };

const registry = JSON.parse(await readFile(REGISTRY, "utf8")) as { items: RegistryItem[] };

const keys = registry.items
  .flatMap((item) => item.files.map((file) => file.path))
  .filter((file) => file.endsWith(".tsx"))
  .map((file) => file.slice(0, -".tsx".length))
  .sort();

if (keys.length === 0) {
  throw new Error(`scripts/build-demo-map.ts: no .tsx demo files listed in ${REGISTRY}`);
}
if (new Set(keys).size !== keys.length) {
  throw new Error("scripts/build-demo-map.ts: the demos registry lists a demo file twice");
}

const entries = keys.map((key) => `  ${JSON.stringify(key)}: dynamic(() => import("@/demos/${key}")),`);

const source = `// Generated by scripts/build-demo-map.ts from packages/registry/demos/registry.json. Do not edit.
"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";

export const demoMap: Record<string, ComponentType> = {
${entries.join("\n")}
};
`;

let current = "";
try {
  current = await readFile(OUTPUT, "utf8");
} catch {}
if (current !== source) await writeFile(OUTPUT, source);
console.log(`build-demo-map: ${keys.length} demos`);
